export function loadTexts() {
    return [
        {
            "id": 1,
            "text": "Mohandas Karamchand Gandhi foi um advogado, nacionalista, anticolonialista e especialista em ética política indiano, que empregou resistência não violenta para liderar a campanha bem-sucedida para a independência da Índia do Reino Unido, e por sua vez, inspirar movimentos pelos direitos civis e liberdade em todo o mundo. O honorífico Mahatma aplicado a ele pela primeira vez em 1914 na África do Sul, é agora usado em todo o mundo. Nascido e criado em uma família hindu no litoral de Guzerate, oeste da Índia, e formado em direito no Inner Temple, Londres, Gandhi empregou pela primeira vez a desobediência civil não-violenta como advogado expatriado na África do Sul, na luta da comunidade indígena pelos direitos civis. Após seu retorno à Índia em 1915, ele começou a organizar camponeses, agricultores e trabalhadores urbanos para protestar contra o imposto sobre a terra e a discriminação excessiva. Assumindo a liderança do Congresso Nacional Indiano em 1921, Gandhi liderou campanhas nacionais"
        },
        {
            "id": 2,
            "text": "Ocorre o fenômeno da Superlua quando esse satélite natural ocupa a posição de maior proximidade com a Terra, apresentando-se aproximadamente 15% maior e com cerca de 30% a mais de luminosidade. O fenômeno torna-se especial quando coincide com a fase cheia, fazendo com que a Lua seja percebida com um tamanho muito superior ao normal. A Lua gira ao redor da Terra em uma trajetória elíptica (oval). A distância média em relação à Terra é de 384.405 km. No perigeu, ponto mais próximo da Terra, a distância chega a 357.448 km; no apogeu, ponto mais afastado da Terra, a distância chega a 405.363 km. Exatamente no dia 14 de novembro de 2016 a Lua esteve na fase cheia e ocupou a posição de maior proximidade da Terra. A última aproximação de forma semelhante ocorreu em 1948 e a próxima vez em que veremos nosso satélite de tão perto será em novembro de 2034!"
        },
        {
            "id": 3,
            "text": "A origem do nome pode ser atribuída aos alemães e americanos. Em meados de 1850, os alemães começaram a produzir novos tipos de salsicha, originalmente inventada pelos babilônios por volta de 1500 a.C. Um cozinheiro na cidade alemã de Frankfurt possuía um cão bassê, dachshund em alemão, e a salsicha feita por ele ficou conhecida por esse nome. Charles Feltman, um imigrante alemão, levou a novidade para os Estados Unidos, por volta de 1880, e lá criou um sanduíche quente feito com pão, salsicha e molhos. O sucesso foi tal, que Feltman abriu seu próprio restaurante. Mas foi nos estádios de futebol americanos que o sanduíche se popularizou. Conta-se que durante um jogo, em1906, um vendedor gritava nas arquibancadas: “Get your hot dachshund” (Pegue seu dachshund quente). O cartunista Tad Dorgan, presente ao estádio, não perdeu a chance de ilustrar a cena. Porém, como não entendida a palavra dachshund, escreveu na legenda: “Get your hot dogs” (Pegue seus cachorros quentes). E o nome pegou."
        },
        {
            "id": 4,
            "text": "O que nos faz destros ou canhotos? Essa pergunta atrai a atenção de cientistas há muito tempo. Uma nova pesquisa indica que tudo que se acreditava até agora está errado. De acordo com cientistas da Ruhr-Universität Bochum, uma universidade alemã, a resposta não está no cérebro, como se acreditava. Os resultados mudam nossa compreensão das causas que levam à assimetria hemisférica, concluem os pesquisadores. Em resumo, o estudo chegou à conclusão que a assimetria hemisférica, basicamente a causa de sermos destros ou canhotos, está determinada desde o útero. A pesquisa afirma que na 13ª semana, fetos já demonstram preferência por um dos lados do corpo para a realização de movimentos na gestação. Exames de ultrassom mostraram que essa inclinação a usar uma das mãos, por exemplo, começa a ser definida na oitava semana de gestação. Ao contrário do que se acreditava, essa característica não é definida por características cerebrais. A grande responsável por uma pessoa ser destra ou canhota é sua medula espinhal."
        }
    ]
}